### ISSUE TITLE
Crashes after confirming photo taken with device

### ISSUE THREAD

**Issue by stevelyall** [binder-app/android#20]
@roddicks I know you're not done with the FirstLaunchActivity just yet, though working on it I'm getting a crash on my device once I take my photo and tap the checkmark to confirm it. 

Does this work on your devices? Or is it a device specific issue for me?

```
ca.binder E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: ca.binder, PID: 32383
                                                           java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9999, result=-1, data=Intent {  }} to activity {ca.binder/ca.binder.FirstLaunchActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference
                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                               at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                            Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference
                                                               at ca.binder.BinderUtilities.findImageFileFromUri(BinderUtilities.java:30)
                                                               at ca.binder.FirstLaunchActivity.onActivityResult(FirstLaunchActivity.java:106)
                                                               at android.app.Activity.dispatchActivityResult(Activity.java:6428)
                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
                                                               at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:148) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by stevelyall** [comment]
This may be dependent on Issue #25

**Comment by mitchhentges** [comment]
@stevelyall, are you still getting this?

**Comment by mitchhentges** [comment]
Nvm, finally reproduced it. Took a little, heh
