### ISSUE TITLE
Add photo taken to profile during profile creation

### ISSUE THREAD

**Issue by stevelyall** [binder-app/android#26]
Send to server with other profile data

**Comment by stevelyall** [comment]
Getting a crash after pushing the Start Binding button....will fix

```
11-16 13:36:59.949 1630-1630/ca.binder E/AndroidRuntime: FATAL EXCEPTION: main
                                                         Process: ca.binder, PID: 1630
                                                         java.lang.IllegalStateException: Could not execute method of the activity
                                                             at android.view.View$1.onClick(View.java:3823)
                                                             at android.view.View.performClick(View.java:4438)
                                                             at android.view.View$PerformClick.run(View.java:18422)
                                                             at android.os.Handler.handleCallback(Handler.java:733)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:136)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                             at dalvik.system.NativeStart.main(Native Method)
                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                             at android.view.View$1.onClick(View.java:3818)
                                                             at android.view.View.performClick(View.java:4438) 
                                                             at android.view.View$PerformClick.run(View.java:18422) 
                                                             at android.os.Handler.handleCallback(Handler.java:733) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                             at android.os.Looper.loop(Looper.java:136) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                          Caused by: java.lang.ClassCastException: android.widget.Spinner cannot be cast to android.widget.EditText
                                                             at ca.binder.FirstLaunchActivity.text(FirstLaunchActivity.java:180)
                                                             at ca.binder.FirstLaunchActivity.createProfile(FirstLaunchActivity.java:135)
                                                             at ca.binder.FirstLaunchActivity.onFinishSetup(FirstLaunchActivity.java:99)
```
