### ISSUE TITLE
Crashes on subsequent launches after clean install

### ISSUE THREAD

**Issue by stevelyall** [binder-app/android#63]
Nexus 5 Android 6.0

https://www.dropbox.com/s/ce6hf8k3awq8kbd/device-2015-11-22-200347.mp4?dl=0

Steps to reproduce:
1. Uninstall the app
2. Install the app
3. Create a test profile including a picture
4. The suggestion view activity is displayed. Exit the app.
5. Relaunch the app.

```
 FATAL EXCEPTION: main
                                                           Process: ca.binder, PID: 32515
                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                               at ca.binder.remote.Photo.base64(Photo.java:40)
                                                               at ca.binder.domain.Match.writeToParcel(Match.java:119)
                                                               at android.os.Parcel.writeParcelable(Parcel.java:1416)
                                                               at android.os.Parcel.writeValue(Parcel.java:1322)
                                                               at android.os.Parcel.writeList(Parcel.java:738)
                                                               at android.os.Parcel.writeValue(Parcel.java:1344)
                                                               at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
                                                               at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                               at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                               at android.os.Parcel.writeBundle(Parcel.java:690)
                                                               at android.content.Intent.writeToParcel(Intent.java:7788)
                                                               at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2639)
                                                               at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
                                                               at android.app.Activity.startActivityForResult(Activity.java:3917)
                                                               at android.app.Activity.startActivityForResult(Activity.java:3877)
                                                               at android.app.Activity.startActivity(Activity.java:4200)
                                                               at android.app.Activity.startActivity(Activity.java:4168)
                                                               at ca.binder.MainActivity$1.use(MainActivity.java:106)
                                                               at ca.binder.remote.request.AsyncServerRequest$1$1.run(AsyncServerRequest.java:33)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by stevelyall** [comment]
Issue is no longer present after clearing the database. Test profiles without photos saved in the db may have been the cause.
